import { Question } from "./types";

export const questions: Question[] = [
  // ===== 数学（Math） =====
  {
    id: "m1",
    subject: "math",
    difficulty: 1,
    question: "3 × 7 はいくつ？",
    choices: ["18", "21", "24", "27"],
    answer: 1,
    explanation: "3 × 7 = 21 だよ！九九の「さんしち21」！",
    xpReward: 10,
  },
  {
    id: "m2",
    subject: "math",
    difficulty: 1,
    question: "48 ÷ 6 はいくつ？",
    choices: ["6", "7", "8", "9"],
    answer: 2,
    explanation: "48 ÷ 6 = 8 だよ！6 × 8 = 48 で確認できるね。",
    xpReward: 10,
  },
  {
    id: "m3",
    subject: "math",
    difficulty: 1,
    question: "正の数と負の数で、(-3) + 5 はいくつ？",
    choices: ["-8", "-2", "2", "8"],
    answer: 2,
    explanation: "数直線で考えると、-3 から 5 進むと 2 になるよ！",
    xpReward: 15,
  },
  {
    id: "m4",
    subject: "math",
    difficulty: 1,
    question: "(-4) × (-3) はいくつ？",
    choices: ["-12", "-7", "7", "12"],
    answer: 3,
    explanation: "マイナス × マイナス = プラス！(-4) × (-3) = 12 だよ。",
    xpReward: 15,
  },
  {
    id: "m5",
    subject: "math",
    difficulty: 1,
    question: "x + 3 = 7 のとき、x はいくつ？",
    choices: ["3", "4", "5", "10"],
    answer: 1,
    explanation: "両辺から 3 を引くと x = 7 - 3 = 4 だよ！",
    xpReward: 15,
  },
  {
    id: "m6",
    subject: "math",
    difficulty: 2,
    question: "2x - 4 = 10 のとき、x はいくつ？",
    choices: ["3", "5", "7", "9"],
    answer: 2,
    explanation: "両辺に 4 を足すと 2x = 14、x = 7 だよ！",
    xpReward: 20,
  },
  {
    id: "m7",
    subject: "math",
    difficulty: 2,
    question: "比例 y = 3x で、x = 4 のとき y はいくつ？",
    choices: ["7", "10", "12", "15"],
    answer: 2,
    explanation: "y = 3 × 4 = 12 だよ！x に 4 を代入するだけ。",
    xpReward: 20,
  },
  {
    id: "m8",
    subject: "math",
    difficulty: 2,
    question: "正三角形の内角の合計は何度？",
    choices: ["90°", "120°", "180°", "360°"],
    answer: 2,
    explanation: "三角形の内角の和はいつでも 180°！正三角形なら各角 60°。",
    xpReward: 20,
  },
  {
    id: "m9",
    subject: "math",
    difficulty: 2,
    question: "面積が 24cm² の長方形で、縦が 4cm なら横は何 cm？",
    choices: ["4cm", "6cm", "8cm", "20cm"],
    answer: 1,
    explanation: "面積 = 縦 × 横 なので 横 = 24 ÷ 4 = 6cm だよ！",
    xpReward: 20,
  },
  {
    id: "m10",
    subject: "math",
    difficulty: 1,
    question: "(-6) ÷ 2 はいくつ？",
    choices: ["-4", "-3", "3", "4"],
    answer: 1,
    explanation: "マイナス ÷ プラス = マイナス。-6 ÷ 2 = -3 だよ！",
    xpReward: 15,
  },
  {
    id: "m11",
    subject: "math",
    difficulty: 1,
    question: "絶対値 |-5| はいくつ？",
    choices: ["-5", "0", "5", "25"],
    answer: 2,
    explanation: "絶対値は数直線上での 0 からの距離。|-5| = 5 だよ！",
    xpReward: 15,
  },
  {
    id: "m12",
    subject: "math",
    difficulty: 2,
    question: "3a + 2a を計算すると？",
    choices: ["5a", "6a", "5a²", "6a²"],
    answer: 0,
    explanation: "文字が同じ項はまとめられる！3a + 2a = 5a だよ。",
    xpReward: 20,
  },

  // ===== 国語（Japanese） =====
  {
    id: "j1",
    subject: "japanese",
    difficulty: 1,
    question: "「快晴」の読み方は？",
    choices: ["かいせい", "こうせい", "かいすい", "こうすい"],
    answer: 0,
    explanation: "「快晴」は「かいせい」！雲ひとつない晴れた天気のことだよ。",
    xpReward: 10,
  },
  {
    id: "j2",
    subject: "japanese",
    difficulty: 1,
    question: "「山」の対義語（反対の意味の言葉）は？",
    choices: ["川", "海", "谷", "空"],
    answer: 2,
    explanation: "「山」の対義語は「谷」！山の反対は谷（低い地形）だよ。",
    xpReward: 10,
  },
  {
    id: "j3",
    subject: "japanese",
    difficulty: 1,
    question: "「僕は毎朝ご飯を食べる。」の主語は？",
    choices: ["毎朝", "ご飯を", "食べる", "僕は"],
    answer: 3,
    explanation: "主語は「何が・誰が」にあたる言葉。「僕は」が主語だよ！",
    xpReward: 10,
  },
  {
    id: "j4",
    subject: "japanese",
    difficulty: 1,
    question: "「走る」の連用形は？",
    choices: ["走ら", "走り", "走れ", "走ろ"],
    answer: 1,
    explanation: "連用形は「〜ます」につく形。「走ります」→「走り」が連用形！",
    xpReward: 15,
  },
  {
    id: "j5",
    subject: "japanese",
    difficulty: 1,
    question: "敬語で「食べる」の丁寧語は？",
    choices: ["召し上がる", "いただく", "食べます", "食べられる"],
    answer: 2,
    explanation: "丁寧語は「〜ます・〜です」をつけるだけ。「食べます」が丁寧語！",
    xpReward: 10,
  },
  {
    id: "j6",
    subject: "japanese",
    difficulty: 2,
    question: "「雨降って地固まる」のことわざの意味は？",
    choices: [
      "雨が降ると道がぬかるむ",
      "もめごとの後はかえって関係が良くなる",
      "雨の日は外出しないほうがよい",
      "天気は急に変わる",
    ],
    answer: 1,
    explanation: "もめごとや困難の後は、かえって物事がしっかり固まるという意味だよ！",
    xpReward: 20,
  },
  {
    id: "j7",
    subject: "japanese",
    difficulty: 1,
    question: "「熱心」の類義語は？",
    choices: ["冷静", "真剣", "軽率", "消極的"],
    answer: 1,
    explanation: "「熱心」も「真剣」も一生懸命取り組む様子を表すよ！",
    xpReward: 15,
  },
  {
    id: "j8",
    subject: "japanese",
    difficulty: 2,
    question: "「枕草子」を書いたのは誰？",
    choices: ["紫式部", "清少納言", "松尾芭蕉", "夏目漱石"],
    answer: 1,
    explanation: "「枕草子」は清少納言が書いたエッセイ（随筆）だよ！「春はあけぼの」が有名。",
    xpReward: 20,
  },
  {
    id: "j9",
    subject: "japanese",
    difficulty: 1,
    question: "「泣く」の反対語（対義語）は？",
    choices: ["怒る", "笑う", "走る", "眠る"],
    answer: 1,
    explanation: "「泣く」の対義語は「笑う」だよ！感情の反対を考えよう。",
    xpReward: 10,
  },
  {
    id: "j10",
    subject: "japanese",
    difficulty: 2,
    question: "「彼は\\_\\_\\_走った。」の空欄に入る副詞は？",
    choices: ["にこにこ", "ぐんぐん", "きらきら", "ふわふわ"],
    answer: 1,
    explanation: "「ぐんぐん」は勢いよく速く進む様子を表す副詞だよ！",
    xpReward: 20,
  },

  // ===== 理科（Science） - ボーナスXP =====
  {
    id: "s1",
    subject: "science",
    difficulty: 1,
    question: "水が沸騰する温度は何℃？（1気圧）",
    choices: ["80℃", "90℃", "100℃", "120℃"],
    answer: 2,
    explanation: "水は1気圧では100℃で沸騰するよ！これを沸点という。",
    xpReward: 15,
  },
  {
    id: "s2",
    subject: "science",
    difficulty: 1,
    question: "植物が光合成で使うのは何？",
    choices: ["酸素と水", "二酸化炭素と水", "窒素と酸素", "水素と酸素"],
    answer: 1,
    explanation: "光合成は「二酸化炭素 + 水 + 光 → 酸素 + でんぷん」だよ！",
    xpReward: 15,
  },
  {
    id: "s3",
    subject: "science",
    difficulty: 1,
    question: "地球の表面の約何%が海？",
    choices: ["50%", "60%", "70%", "80%"],
    answer: 2,
    explanation: "地球の表面の約70%が海！だから「水の惑星」と呼ばれるよ。",
    xpReward: 15,
  },
  {
    id: "s4",
    subject: "science",
    difficulty: 1,
    question: "力の単位は？",
    choices: ["ジュール", "ワット", "ニュートン", "パスカル"],
    answer: 2,
    explanation: "力の単位はニュートン（N）！万有引力を発見したニュートンにちなんでいるよ。",
    xpReward: 15,
  },
  {
    id: "s5",
    subject: "science",
    difficulty: 1,
    question: "動物の細胞にあって、植物の細胞にないものは？",
    choices: ["細胞膜", "細胞壁", "核", "ミトコンドリア"],
    answer: 1,
    explanation: "細胞壁は植物細胞にはあるけど、動物細胞にはないよ！",
    xpReward: 15,
  },
  {
    id: "s6",
    subject: "science",
    difficulty: 2,
    question: "密度の計算式は？",
    choices: [
      "密度 = 質量 × 体積",
      "密度 = 質量 ÷ 体積",
      "密度 = 体積 ÷ 質量",
      "密度 = 質量 + 体積",
    ],
    answer: 1,
    explanation: "密度 = 質量 ÷ 体積！単位は g/cm³ だよ。物質ごとに決まった値がある。",
    xpReward: 25,
  },
  {
    id: "s7",
    subject: "science",
    difficulty: 1,
    question: "月が光って見える理由は？",
    choices: [
      "月自身が光を出している",
      "太陽の光を反射している",
      "地球の光を反射している",
      "星の光を集めている",
    ],
    answer: 1,
    explanation: "月は自分では光らない！太陽の光を反射して光って見えるんだよ。",
    xpReward: 15,
  },
  {
    id: "s8",
    subject: "science",
    difficulty: 2,
    question: "音が伝わる速さ（音速）は空気中で約何 m/s？",
    choices: ["34 m/s", "340 m/s", "3400 m/s", "34000 m/s"],
    answer: 1,
    explanation: "音速は約340 m/s！光の速さ（約30万 km/s）より全然遅いよ。",
    xpReward: 25,
  },
  {
    id: "s9",
    subject: "science",
    difficulty: 1,
    question: "火山から出る溶けた岩石を何という？",
    choices: ["マグマ", "溶岩", "岩漿", "花崗岩"],
    answer: 1,
    explanation: "地下にあるときはマグマ、地表に出てきたら溶岩（ようがん）と呼ぶよ！",
    xpReward: 15,
  },
  {
    id: "s10",
    subject: "science",
    difficulty: 2,
    question: "電気抵抗の単位は？",
    choices: ["アンペア", "ボルト", "オーム", "ワット"],
    answer: 2,
    explanation: "電気抵抗の単位はオーム（Ω）！オームの法則 V = IR で使うよ。",
    xpReward: 25,
  },
  {
    id: "s11",
    subject: "science",
    difficulty: 1,
    question: "ヒトの体で最も大きい臓器は？",
    choices: ["肺", "肝臓", "心臓", "胃"],
    answer: 1,
    explanation: "体の中で最も大きい臓器は肝臓！解毒や栄養の貯蔵など大事な働きをするよ。",
    xpReward: 15,
  },
  {
    id: "s12",
    subject: "science",
    difficulty: 2,
    question: "地震の揺れの大きさを表す単位は？",
    choices: ["マグニチュード", "震度", "デシベル", "ガル"],
    answer: 1,
    explanation: "震度は「その場所の揺れの強さ」。マグニチュードは地震自体のエネルギーの大きさだよ！",
    xpReward: 25,
  },
];

export function getQuestionsBySubject(subject: string): Question[] {
  return questions.filter((q) => q.subject === subject);
}

export function getRandomQuestions(subject: string, count: number): Question[] {
  const filtered = getQuestionsBySubject(subject);
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
