import { Question } from "./types";

export const questions: Question[] = [
  // ===== 数学（小学2年〜6年） =====
  {
    id: "m1",
    subject: "math",
    difficulty: 1,
    question: "8 × 7 はいくつ？",
    choices: ["54", "56", "63", "64"],
    answer: 1,
    explanation: "8 × 7 = 56 だよ！九九の「はちしち56」！",
    xpReward: 10,
  },
  {
    id: "m2",
    subject: "math",
    difficulty: 1,
    question: "9 × 6 はいくつ？",
    choices: ["48", "52", "54", "56"],
    answer: 2,
    explanation: "9 × 6 = 54 だよ！九九の「くろく54」！",
    xpReward: 10,
  },
  {
    id: "m3",
    subject: "math",
    difficulty: 1,
    question: "72 ÷ 8 はいくつ？",
    choices: ["7", "8", "9", "10"],
    answer: 2,
    explanation: "8 × 9 = 72 だから、72 ÷ 8 = 9 だよ！",
    xpReward: 10,
  },
  {
    id: "m4",
    subject: "math",
    difficulty: 1,
    question: "345 + 278 はいくつ？",
    choices: ["513", "623", "623", "633"],
    answer: 1,
    explanation: "筆算で計算すると 345 + 278 = 623 だよ！くり上がりに注意しよう。",
    xpReward: 10,
  },
  {
    id: "m5",
    subject: "math",
    difficulty: 1,
    question: "503 − 247 はいくつ？",
    choices: ["246", "256", "266", "354"],
    answer: 1,
    explanation: "503 − 247 = 256 だよ！くり下がりに注意しよう。",
    xpReward: 10,
  },
  {
    id: "m6",
    subject: "math",
    difficulty: 2,
    question: "1/3 + 1/3 はいくつ？",
    choices: ["1/6", "1/3", "2/3", "2/6"],
    answer: 2,
    explanation: "分母が同じ分数はそのまま分子だけたす。1/3 + 1/3 = 2/3 だよ！",
    xpReward: 15,
  },
  {
    id: "m7",
    subject: "math",
    difficulty: 2,
    question: "3/4 − 1/4 はいくつ？",
    choices: ["1/4", "1/2", "2/4", "3/4"],
    answer: 1,
    explanation: "3/4 − 1/4 = 2/4 = 1/2 だよ！約分を忘れずに！",
    xpReward: 15,
  },
  {
    id: "m8",
    subject: "math",
    difficulty: 2,
    question: "面積が 24cm² の長方形、縦が 4cm なら横は何 cm？",
    choices: ["4cm", "6cm", "8cm", "20cm"],
    answer: 1,
    explanation: "面積 = 縦 × 横 なので、横 = 24 ÷ 4 = 6cm だよ！",
    xpReward: 15,
  },
  {
    id: "m9",
    subject: "math",
    difficulty: 2,
    question: "40人のクラスで、好きな人が30人。これは全体の何%？",
    choices: ["25%", "30%", "65%", "75%"],
    answer: 3,
    explanation: "30 ÷ 40 × 100 = 75% だよ！百分率は「÷全体×100」で出せる！",
    xpReward: 20,
  },
  {
    id: "m10",
    subject: "math",
    difficulty: 2,
    question: "半径 5cm の円の面積はいくつ？（π = 3.14）",
    choices: ["15.7cm²", "31.4cm²", "78.5cm²", "157cm²"],
    answer: 2,
    explanation: "円の面積 = 半径 × 半径 × π = 5 × 5 × 3.14 = 78.5cm² だよ！",
    xpReward: 20,
  },
  {
    id: "m11",
    subject: "math",
    difficulty: 1,
    question: "2.4 × 3 はいくつ？",
    choices: ["6.2", "7.0", "7.2", "7.4"],
    answer: 2,
    explanation: "2.4 × 3 = 7.2 だよ！小数点の位置に気をつけよう。",
    xpReward: 10,
  },
  {
    id: "m12",
    subject: "math",
    difficulty: 2,
    question: "速さ 60km/h で 2 時間 30 分走ると何 km？",
    choices: ["90km", "120km", "150km", "180km"],
    answer: 2,
    explanation: "2時間30分 = 2.5時間。60 × 2.5 = 150km だよ！「道のり = 速さ × 時間」",
    xpReward: 20,
  },
  {
    id: "m13",
    subject: "math",
    difficulty: 1,
    question: "三角形の面積の公式は？",
    choices: ["底辺 × 高さ", "底辺 × 高さ ÷ 2", "底辺 + 高さ × 2", "底辺 × 高さ × 2"],
    answer: 1,
    explanation: "三角形の面積 = 底辺 × 高さ ÷ 2 だよ！長方形の半分って覚えよう。",
    xpReward: 10,
  },
  {
    id: "m14",
    subject: "math",
    difficulty: 2,
    question: "1/2 × 3/4 はいくつ？",
    choices: ["3/2", "4/6", "3/8", "4/8"],
    answer: 2,
    explanation: "分数のかけ算は分子同士・分母同士をかける。1×3 / 2×4 = 3/8 だよ！",
    xpReward: 15,
  },
  {
    id: "m15",
    subject: "math",
    difficulty: 3,
    question: "比例式 x : 4 = 6 : 8 のとき、x はいくつ？",
    choices: ["2", "3", "4", "6"],
    answer: 1,
    explanation: "内側同士・外側同士をかけて等しい。x × 8 = 4 × 6 = 24。x = 24 ÷ 8 = 3 だよ！",
    xpReward: 25,
  },

  // ===== 国語（漢字検定 小学5年〜中学1年レベル） =====
  {
    id: "j1",
    subject: "japanese",
    difficulty: 1,
    question: "「快晴」の読み方は？",
    choices: ["かいすい", "かいせい", "こうせい", "こうすい"],
    answer: 1,
    explanation: "「快晴」は「かいせい」！雲ひとつない晴れた天気のこと。「快」＝気持ちよい。",
    xpReward: 10,
  },
  {
    id: "j2",
    subject: "japanese",
    difficulty: 1,
    question: "「永遠」の読み方は？",
    choices: ["えいえん", "ながとお", "えいとお", "ながえん"],
    answer: 0,
    explanation: "「永遠」は「えいえん」！いつまでも続くという意味だよ。",
    xpReward: 10,
  },
  {
    id: "j3",
    subject: "japanese",
    difficulty: 1,
    question: "「賛成」の読み方は？",
    choices: ["さんぜい", "さんせい", "さんじょう", "ざんせい"],
    answer: 1,
    explanation: "「賛成」は「さんせい」！相手の意見に同意するときに使うよ。",
    xpReward: 10,
  },
  {
    id: "j4",
    subject: "japanese",
    difficulty: 1,
    question: "「にっき」を漢字で書くと？",
    choices: ["日記", "日紀", "日季", "日起"],
    answer: 0,
    explanation: "「日記」が正しい！毎日の出来事を書くものだよ。",
    xpReward: 10,
  },
  {
    id: "j5",
    subject: "japanese",
    difficulty: 1,
    question: "「ひつよう」を漢字で書くと？",
    choices: ["必要", "必葉", "必用", "必容"],
    answer: 0,
    explanation: "「必要」が正しい！「必ず要る（いる）」と覚えよう。",
    xpReward: 10,
  },
  {
    id: "j6",
    subject: "japanese",
    difficulty: 2,
    question: "「危険」の読み方は？",
    choices: ["きけん", "ひけん", "きがい", "あぶけん"],
    answer: 0,
    explanation: "「危険」は「きけん」！あぶないことを表すよ。",
    xpReward: 15,
  },
  {
    id: "j7",
    subject: "japanese",
    difficulty: 2,
    question: "「拡大」の読み方は？",
    choices: ["こうたい", "かくだい", "こうだい", "かくたい"],
    answer: 1,
    explanation: "「拡大」は「かくだい」！大きくひろげること。反対は「縮小」。",
    xpReward: 15,
  },
  {
    id: "j8",
    subject: "japanese",
    difficulty: 2,
    question: "「ぞうか」を漢字で書くと？（数が増えること）",
    choices: ["増化", "増加", "層加", "増果"],
    answer: 1,
    explanation: "「増加」が正しい！「増える」＋「加わる」で数が多くなること。",
    xpReward: 15,
  },
  {
    id: "j9",
    subject: "japanese",
    difficulty: 2,
    question: "「げんいん」を漢字で書くと？",
    choices: ["原員", "元因", "原因", "源因"],
    answer: 2,
    explanation: "「原因」が正しい！何かが起こったもとの理由のこと。",
    xpReward: 15,
  },
  {
    id: "j10",
    subject: "japanese",
    difficulty: 2,
    question: "「異常」の「異」と同じ読みの漢字は？",
    choices: ["以", "移", "意", "医"],
    answer: 1,
    explanation: "「異常（いじょう）」の「異（い）」と同じ読みは「移（い）動」の「移」だよ！",
    xpReward: 20,
  },
  {
    id: "j11",
    subject: "japanese",
    difficulty: 3,
    question: "「暖かい」と「温かい」の使い分けで正しいのは？",
    choices: [
      "どちらも同じ意味で使い方は同じ",
      "「暖かい」は気候・気温、「温かい」は物の温度や気持ち",
      "「温かい」は気候、「暖かい」は食べ物",
      "「暖かい」は夏に、「温かい」は冬に使う",
    ],
    answer: 1,
    explanation: "「暖かい春の日」など気候には「暖」、「温かいスープ」「温かい言葉」など物・気持ちには「温」を使うよ！",
    xpReward: 25,
  },
  {
    id: "j12",
    subject: "japanese",
    difficulty: 2,
    question: "「縮小」の対義語（反対の意味）は？",
    choices: ["減少", "拡大", "圧縮", "延長"],
    answer: 1,
    explanation: "「縮小（ちぢめて小さくする）」の反対は「拡大（ひろげて大きくする）」だよ！",
    xpReward: 15,
  },
  {
    id: "j13",
    subject: "japanese",
    difficulty: 1,
    question: "「せいかく」（正しくて間違いがない）を漢字で書くと？",
    choices: ["正格", "精確", "正確", "正覚"],
    answer: 2,
    explanation: "「正確」が正しい！「正しく確か」と覚えよう。",
    xpReward: 10,
  },
  {
    id: "j14",
    subject: "japanese",
    difficulty: 3,
    question: "「以心伝心」の意味は？",
    choices: [
      "心を込めて手紙を送ること",
      "言葉を使わなくても気持ちが伝わること",
      "心が広い人のこと",
      "大切な伝言を伝えること",
    ],
    answer: 1,
    explanation: "「以心伝心（いしんでんしん）」は言葉がなくても気持ちが通じ合うこと。四字熟語だよ！",
    xpReward: 25,
  },
  {
    id: "j15",
    subject: "japanese",
    difficulty: 2,
    question: "「投票」の「票」の部首は？",
    choices: ["木", "示", "西", "火"],
    answer: 1,
    explanation: "「票」の部首は「示（しめすへん）」だよ。票・標・示などに使われているよ。",
    xpReward: 15,
  },

  // ===== 論理的思考力 =====
  {
    id: "l1",
    subject: "logic",
    difficulty: 1,
    question: "AはBより背が高い。BはCより背が高い。一番背が低いのは誰？",
    choices: ["A", "B", "C", "わからない"],
    answer: 2,
    explanation: "A > B > C の順番。一番低いのは C だよ！「AはBより高い」→AはBの上、と順番に並べて考えよう。",
    xpReward: 15,
  },
  {
    id: "l2",
    subject: "logic",
    difficulty: 1,
    question: "1, 3, 5, 7, □ ── □に入る数は？",
    choices: ["8", "9", "10", "11"],
    answer: 1,
    explanation: "2ずつ増える数列（奇数の並び）！7 + 2 = 9 だよ。",
    xpReward: 15,
  },
  {
    id: "l3",
    subject: "logic",
    difficulty: 1,
    question: "2, 4, 8, 16, □ ── □に入る数は？",
    choices: ["18", "24", "32", "64"],
    answer: 2,
    explanation: "2倍ずつ増える数列！16 × 2 = 32 だよ。",
    xpReward: 15,
  },
  {
    id: "l4",
    subject: "logic",
    difficulty: 2,
    question: "「すべての犬は動物だ。ポチは犬だ。」ならポチは？",
    choices: ["動物ではない", "動物だ", "犬ではないかもしれない", "わからない"],
    answer: 1,
    explanation: "「すべての犬は動物」＋「ポチは犬」→「ポチは動物」。三段論法だよ！",
    xpReward: 20,
  },
  {
    id: "l5",
    subject: "logic",
    difficulty: 2,
    question: "5人が1列に並ぶ。AはBの右隣。BはCの右隣。CはDの右隣。左から2番目は誰？",
    choices: ["A", "B", "C", "D"],
    answer: 2,
    explanation: "右から並べると A→B→C→D の順。左からだとD,C,B,A…左から2番目はC だよ！",
    xpReward: 20,
  },
  {
    id: "l6",
    subject: "logic",
    difficulty: 2,
    question: "太郎・次郎・三郎の3人のうち1人だけ嘘をつく。「太郎：私は正直」「次郎：太郎は嘘つき」「三郎：次郎は正直」。嘘つきは誰？",
    choices: ["太郎", "次郎", "三郎", "わからない"],
    answer: 1,
    explanation: "太郎が正直なら「私は正直」は本当→次郎の「太郎は嘘つき」が嘘→次郎が嘘つき。矛盾なし！次郎が嘘つき。",
    xpReward: 25,
  },
  {
    id: "l7",
    subject: "logic",
    difficulty: 1,
    question: "1, 4, 9, 16, □ ── □に入る数は？",
    choices: ["20", "25", "36", "49"],
    answer: 1,
    explanation: "1²=1, 2²=4, 3²=9, 4²=16, 5²=25。これは「二乗の数列」だよ！",
    xpReward: 15,
  },
  {
    id: "l8",
    subject: "logic",
    difficulty: 2,
    question: "赤・青・黄の3色で旗を作る。左・中・右の3つに色を塗る（同じ色は隣に使えない）。何通り？",
    choices: ["6通り", "12通り", "18通り", "24通り"],
    answer: 1,
    explanation: "左：3通り→中：2通り（左と違う）→右：2通り（中と違う）。3×2×2=12通りだよ！",
    xpReward: 20,
  },
  {
    id: "l9",
    subject: "logic",
    difficulty: 2,
    question: "「雨なら運動会は中止」「今日は運動会が行われた」。今日の天気は？",
    choices: ["雨だった", "雨でなかった", "くもりだった", "わからない"],
    answer: 1,
    explanation: "「雨→中止」の対偶は「中止でない→雨でない」。運動会が行われた＝中止でない→雨でなかった！",
    xpReward: 20,
  },
  {
    id: "l10",
    subject: "logic",
    difficulty: 1,
    question: "図形の規則：○△○△○△…の10番目は何？",
    choices: ["○", "△", "どちらでもない", "わからない"],
    answer: 1,
    explanation: "2つのくり返し。10 ÷ 2 = 5 でちょうど割り切れるから偶数番目→△ だよ！",
    xpReward: 15,
  },
  {
    id: "l11",
    subject: "logic",
    difficulty: 3,
    question: "Aが「BはCより速い」、BがAより速い」とすると、最も速いのは誰？",
    choices: ["A", "B", "C", "わからない"],
    answer: 1,
    explanation: "B > A（BはAより速い）、B > C（BはCより速い）。Bが一番速い！",
    xpReward: 25,
  },
  {
    id: "l12",
    subject: "logic",
    difficulty: 2,
    question: "100円・50円・10円を使って、ちょうど160円にする組み合わせは何通り？（全種類使わなくてよい）",
    choices: ["3通り", "4通り", "5通り", "6通り"],
    answer: 0,
    explanation: "①100+50+10=160 ②100+60（10×6）=160 ③50×3+10=160 の3通り！表を作って整理しよう。",
    xpReward: 20,
  },
  {
    id: "l13",
    subject: "logic",
    difficulty: 1,
    question: "「猫は魚が好き」「タマは猫だ」→タマは何が好き？",
    choices: ["肉", "魚", "野菜", "わからない"],
    answer: 1,
    explanation: "「すべての猫は魚が好き」＋「タマは猫」→「タマは魚が好き」。シンプルな三段論法！",
    xpReward: 15,
  },
  {
    id: "l14",
    subject: "logic",
    difficulty: 3,
    question: "1〜9のカードから3枚選んで3ケタの数を作る。最大と最小の差は？（987と123）",
    choices: ["754", "864", "864", "876"],
    answer: 2,
    explanation: "最大：9×100+8×10+7=987、最小：1×100+2×10+3=123。987-123=864 だよ！",
    xpReward: 25,
  },
  {
    id: "l15",
    subject: "logic",
    difficulty: 2,
    question: "「AかBのどちらかは必ず参加する」「Aは参加しない」→Bは？",
    choices: ["参加しない", "必ず参加する", "参加するかもしれない", "わからない"],
    answer: 1,
    explanation: "「AかB少なくとも一方が参加」＋「Aは参加しない」→Bは必ず参加！選言三段論法だよ。",
    xpReward: 20,
  },
];

export function getQuestionsBySubject(subject: string): Question[] {
  return questions.filter((q) => q.subject === subject);
}

export function getRandomQuestions(subject: string, count: number): Question[] {
  const filtered = getQuestionsBySubject(subject);
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
